// Irish towns and cities mapped to their counties
export const IRISH_TOWNS: Record<string, string> = {
  // Dublin
  'Dublin': 'Dublin',
  'Dún Laoghaire': 'Dublin',
  'Swords': 'Dublin',
  'Tallaght': 'Dublin',
  'Blanchardstown': 'Dublin',
  'Lucan': 'Dublin',
  'Clondalkin': 'Dublin',
  'Finglas': 'Dublin',
  'Santry': 'Dublin',
  'Howth': 'Dublin',
  'Malahide': 'Dublin',
  'Skerries': 'Dublin',
  'Rush': 'Dublin',
  'Lusk': 'Dublin',
  'Balbriggan': 'Dublin',
  'Donabate': 'Dublin',
  'Portmarnock': 'Dublin',
  'Sutton': 'Dublin',
  'Raheny': 'Dublin',
  'Clontarf': 'Dublin',
  'Drumcondra': 'Dublin',
  'Phibsborough': 'Dublin',
  'Rathmines': 'Dublin',
  'Ranelagh': 'Dublin',
  'Ballsbridge': 'Dublin',
  'Sandymount': 'Dublin',
  'Blackrock': 'Dublin',
  'Dún Laoghaire': 'Dublin',
  'Dalkey': 'Dublin',
  'Killiney': 'Dublin',
  'Shankill': 'Dublin',
  'Bray': 'Wicklow', // Note: Bray is in Wicklow but close to Dublin
  'Cabinteely': 'Dublin',
  'Foxrock': 'Dublin',
  'Stillorgan': 'Dublin',
  'Dundrum': 'Dublin',
  'Rathfarnham': 'Dublin',
  'Terenure': 'Dublin',
  'Crumlin': 'Dublin',
  'Walkinstown': 'Dublin',
  'Ballyfermot': 'Dublin',
  'Chapelizod': 'Dublin',
  'Castleknock': 'Dublin',
  'Clonee': 'Meath', // Close to Dublin border
  
  // Cork
  'Cork': 'Cork',
  'Cobh': 'Cork',
  'Youghal': 'Cork',
  'Kinsale': 'Cork',
  'Midleton': 'Cork',
  'Fermoy': 'Cork',
  'Mallow': 'Cork',
  'Bandon': 'Cork',
  'Clonakilty': 'Cork',
  'Skibbereen': 'Cork',
  'Bantry': 'Cork',
  'Macroom': 'Cork',
  'Kanturk': 'Cork',
  'Charleville': 'Cork',
  'Millstreet': 'Cork',
  'Castletownbere': 'Cork',
  'Schull': 'Cork',
  'Baltimore': 'Cork',
  'Rosscarbery': 'Cork',
  'Dunmanway': 'Cork',
  'Ballydehob': 'Cork',
  'Glandore': 'Cork',
  'Union Hall': 'Cork',
  'Courtmacsherry': 'Cork',
  'Timoleague': 'Cork',
  'Buttevant': 'Cork',
  'Newmarket': 'Cork',
  'Doneraile': 'Cork',
  'Castletownroche': 'Cork',
  'Castlelyons': 'Cork',
  'Glanmire': 'Cork',
  'Blarney': 'Cork',
  'Ballincollig': 'Cork',
  'Douglas': 'Cork',
  'Rochestown': 'Cork',
  'Passage West': 'Cork',
  'Ringaskiddy': 'Cork',
  'Crosshaven': 'Cork',
  'Whitegate': 'Cork',
  'Aghada': 'Cork',
  
  // Galway
  'Galway': 'Galway',
  'Tuam': 'Galway',
  'Ballinasloe': 'Galway',
  'Loughrea': 'Galway',
  'Athenry': 'Galway',
  'Gort': 'Galway',
  'Clifden': 'Galway',
  'Oughterard': 'Galway',
  'Portumna': 'Galway',
  'Headford': 'Galway',
  'Kinvara': 'Galway',
  'Spiddal': 'Galway',
  'An Spidéal': 'Galway',
  'Carna': 'Galway',
  'Roundstone': 'Galway',
  'Moycullen': 'Galway',
  'Craughwell': 'Galway',
  'Mountbellew': 'Galway',
  'Dunmore': 'Galway',
  'Ballygar': 'Galway',
  'Williamstown': 'Galway',
  'Glenamaddy': 'Galway',
  'Milltown': 'Galway',
  'Corofin': 'Galway',
  'Inverin': 'Galway',
  'Carraroe': 'Galway',
  'Lettermore': 'Galway',
  'Costelloe': 'Galway',
  'Barna': 'Galway',
  'Furbo': 'Galway',
  'Kilcolgan': 'Galway',
  'Kilchreest': 'Galway',
  'Killimor': 'Galway',
  'Ahascragh': 'Galway',
  'Aughrim': 'Galway',
  'Ballymoe': 'Galway',
  'Ballygar': 'Galway',
  'Creggs': 'Galway',
  'Dunmore': 'Galway',
  'Glenamaddy': 'Galway',
  'Kilconnell': 'Galway',
  'Newbridge': 'Galway',
  'Williamstown': 'Galway',
  'Woodlawn': 'Galway',
  
  // Limerick
  'Limerick': 'Limerick',
  'Newcastle West': 'Limerick',
  'Kilmallock': 'Limerick',
  'Rathkeale': 'Limerick',
  'Abbeyfeale': 'Limerick',
  'Foynes': 'Limerick',
  'Askeaton': 'Limerick',
  'Adare': 'Limerick',
  'Patrickswell': 'Limerick',
  'Castletroy': 'Limerick',
  'Dooradoyle': 'Limerick',
  'Raheen': 'Limerick',
  'Mungret': 'Limerick',
  'Croom': 'Limerick',
  'Bruff': 'Limerick',
  'Ballingarry': 'Limerick',
  'Ballylanders': 'Limerick',
  'Galbally': 'Limerick',
  'Hospital': 'Limerick',
  'Knocklong': 'Limerick',
  'Caherconlish': 'Limerick',
  'Murroe': 'Limerick',
  'Cappamore': 'Limerick',
  'Pallasgreen': 'Limerick',
  'Oola': 'Limerick',
  
  // Waterford
  'Waterford': 'Waterford',
  'Dungarvan': 'Waterford',
  'Tramore': 'Waterford',
  'Lismore': 'Waterford',
  'Portlaw': 'Waterford',
  'Kilmacthomas': 'Waterford',
  'Dunmore East': 'Waterford',
  'Tramore': 'Waterford',
  'Ardmore': 'Waterford',
  'Youghal': 'Cork', // Note: Youghal is in Cork but close to Waterford border
  'Passage East': 'Waterford',
  'Cheekpoint': 'Waterford',
  'Portlaw': 'Waterford',
  'Carrick-on-Suir': 'Tipperary', // Close to Waterford border
  'Clonmel': 'Tipperary', // Close to Waterford border
  
  // Wicklow
  'Bray': 'Wicklow',
  'Wicklow': 'Wicklow',
  'Greystones': 'Wicklow',
  'Arklow': 'Wicklow',
  'Blessington': 'Wicklow',
  'Newtownmountkennedy': 'Wicklow',
  'Rathnew': 'Wicklow',
  'Enniskerry': 'Wicklow',
  'Kilcoole': 'Wicklow',
  'Newcastle': 'Wicklow',
  'Kilpedder': 'Wicklow',
  'Roundwood': 'Wicklow',
  'Laragh': 'Wicklow',
  'Glendalough': 'Wicklow',
  'Rathdrum': 'Wicklow',
  'Aughrim': 'Wicklow',
  'Tinahely': 'Wicklow',
  'Shillelagh': 'Wicklow',
  'Carnew': 'Wicklow',
  'Bunclody': 'Wexford', // Close to Wicklow border
  'Baltinglass': 'Wicklow',
  'Tullow': 'Carlow', // Close to Wicklow border
  
  // Kildare
  'Newbridge': 'Kildare',
  'Naas': 'Kildare',
  'Athy': 'Kildare',
  'Celbridge': 'Kildare',
  'Leixlip': 'Kildare',
  'Maynooth': 'Kildare',
  'Kildare': 'Kildare',
  'Monasterevin': 'Kildare',
  'Kilcock': 'Kildare',
  'Clane': 'Kildare',
  'Sallins': 'Kildare',
  'Naas': 'Kildare',
  'Kill': 'Kildare',
  'Eadestown': 'Kildare',
  'Brittas': 'Kildare',
  'Blessington': 'Wicklow', // Close to Kildare border
  'Kilcullen': 'Kildare',
  'Castledermot': 'Kildare',
  'Athy': 'Kildare',
  'Monasterevin': 'Kildare',
  'Kildare': 'Kildare',
  'Curragh': 'Kildare',
  'Newbridge': 'Kildare',
  'Suncroft': 'Kildare',
  'Allenwood': 'Kildare',
  'Robertstown': 'Kildare',
  'Prosperous': 'Kildare',
  'Clane': 'Kildare',
  'Straffan': 'Kildare',
  'Celbridge': 'Kildare',
  'Leixlip': 'Kildare',
  'Maynooth': 'Kildare',
  'Kilcock': 'Kildare',
  'Enfield': 'Meath', // Close to Kildare border
  
  // Meath
  'Navan': 'Meath',
  'Trim': 'Meath',
  'Kells': 'Meath',
  'Ashbourne': 'Meath',
  'Drogheda': 'Louth', // Note: Drogheda spans Louth and Meath, but primarily Louth
  'Dunboyne': 'Meath',
  'Slane': 'Meath',
  'Laytown': 'Meath',
  'Bettystown': 'Meath',
  'Drogheda': 'Louth', // Spans both counties
  'Mornington': 'Meath',
  'Donore': 'Meath',
  'Duleek': 'Meath',
  'Stamullen': 'Meath',
  'Gormanston': 'Meath',
  'Balbriggan': 'Dublin', // Close to Meath border
  'Ratoath': 'Meath',
  'Dunshaughlin': 'Meath',
  'Navan': 'Meath',
  'Kells': 'Meath',
  'Oldcastle': 'Meath',
  'Castletown': 'Meath',
  'Trim': 'Meath',
  'Athboy': 'Meath',
  'Kells': 'Meath',
  'Nobber': 'Meath',
  'Virginia': 'Cavan', // Close to Meath border
  
  // Louth
  'Dundalk': 'Louth',
  'Drogheda': 'Louth',
  'Ardee': 'Louth',
  'Carlingford': 'Louth',
  'Blackrock': 'Louth',
  'Termonfeckin': 'Louth',
  'Clogherhead': 'Louth',
  'Drogheda': 'Louth',
  'Dundalk': 'Louth',
  'Ardee': 'Louth',
  'Carlingford': 'Louth',
  'Omeath': 'Louth',
  'Greenore': 'Louth',
  'Dundalk': 'Louth',
  'Castlebellingham': 'Louth',
  'Dunleer': 'Louth',
  'Tallanstown': 'Louth',
  'Louth': 'Louth',
  
  // Wexford
  'Wexford': 'Wexford',
  'Enniscorthy': 'Wexford',
  'Gorey': 'Wexford',
  'New Ross': 'Wexford',
  'Rosslare': 'Wexford',
  'Bunclody': 'Wexford',
  'Enniscorthy': 'Wexford',
  'Ferns': 'Wexford',
  'Gorey': 'Wexford',
  'Courtown': 'Wexford',
  'Arklow': 'Wicklow', // Close to Wexford border
  'Wexford': 'Wexford',
  'Rosslare': 'Wexford',
  'Kilmore Quay': 'Wexford',
  'Fethard-on-Sea': 'Wexford',
  'Duncannon': 'Wexford',
  'New Ross': 'Wexford',
  'Taghmon': 'Wexford',
  'Wexford': 'Wexford',
  'Crossabeg': 'Wexford',
  'Oulart': 'Wexford',
  'Blackwater': 'Wexford',
  'Castletown': 'Wexford',
  'Courtown': 'Wexford',
  'Riverchapel': 'Wexford',
  
  // Kilkenny
  'Kilkenny': 'Kilkenny',
  'Callan': 'Kilkenny',
  'Thomastown': 'Kilkenny',
  'Castlecomer': 'Kilkenny',
  'Graiguenamanagh': 'Kilkenny',
  'Kilkenny': 'Kilkenny',
  'Callan': 'Kilkenny',
  'Thomastown': 'Kilkenny',
  'Inistioge': 'Kilkenny',
  'Bennettsbridge': 'Kilkenny',
  'Gowran': 'Kilkenny',
  'Castlecomer': 'Kilkenny',
  'Ballyragget': 'Kilkenny',
  'Freshford': 'Kilkenny',
  'Urlingford': 'Kilkenny',
  'Johnstown': 'Kilkenny',
  'Goresbridge': 'Kilkenny',
  'Paulstown': 'Kilkenny',
  'Stoneyford': 'Kilkenny',
  'Kells': 'Kilkenny',
  'Dunmore': 'Kilkenny',
  
  // Tipperary
  'Clonmel': 'Tipperary',
  'Nenagh': 'Tipperary',
  'Thurles': 'Tipperary',
  'Carrick-on-Suir': 'Tipperary',
  'Roscrea': 'Tipperary',
  'Cahir': 'Tipperary',
  'Cashel': 'Tipperary',
  'Templemore': 'Tipperary',
  'Thurles': 'Tipperary',
  'Roscrea': 'Tipperary',
  'Nenagh': 'Tipperary',
  'Borrisokane': 'Tipperary',
  'Portumna': 'Galway', // Close to Tipperary border
  'Ballina': 'Tipperary',
  'Killaloe': 'Clare', // Close to Tipperary border
  'Newport': 'Tipperary',
  'Toomevara': 'Tipperary',
  'Moneygall': 'Tipperary',
  'Roscrea': 'Tipperary',
  'Templemore': 'Tipperary',
  'Thurles': 'Tipperary',
  'Holycross': 'Tipperary',
  'Cashel': 'Tipperary',
  'Cahir': 'Tipperary',
  'Clonmel': 'Tipperary',
  'Carrick-on-Suir': 'Tipperary',
  'Fethard': 'Tipperary',
  'Killenaule': 'Tipperary',
  'Mullinahone': 'Tipperary',
  'Callan': 'Kilkenny', // Close to Tipperary border
  
  // Kerry
  'Tralee': 'Kerry',
  'Killarney': 'Kerry',
  'Listowel': 'Kerry',
  'Dingle': 'Kerry',
  'Kenmare': 'Kerry',
  'Caherciveen': 'Kerry',
  'Castleisland': 'Kerry',
  'Tralee': 'Kerry',
  'Killarney': 'Kerry',
  'Listowel': 'Kerry',
  'Dingle': 'Kerry',
  'Kenmare': 'Kerry',
  'Caherciveen': 'Kerry',
  'Sneem': 'Kerry',
  'Waterville': 'Kerry',
  'Caherdaniel': 'Kerry',
  'Ballinskelligs': 'Kerry',
  'Portmagee': 'Kerry',
  'Valentia Island': 'Kerry',
  'Ballybunion': 'Kerry',
  'Ballyheigue': 'Kerry',
  'Fenit': 'Kerry',
  'Ardfert': 'Kerry',
  'Ballyduff': 'Kerry',
  'Abbeydorney': 'Kerry',
  'Lixnaw': 'Kerry',
  'Ballylongford': 'Kerry',
  'Tarbert': 'Kerry',
  'Ballybunion': 'Kerry',
  'Castlegregory': 'Kerry',
  'Camp': 'Kerry',
  'Inch': 'Kerry',
  'Annascaul': 'Kerry',
  'Lispole': 'Kerry',
  'Ventry': 'Kerry',
  'Dunquin': 'Kerry',
  'Ballyferriter': 'Kerry',
  
  // Clare
  'Ennis': 'Clare',
  'Kilrush': 'Clare',
  'Shannon': 'Clare',
  'Kilkee': 'Clare',
  'Lahinch': 'Clare',
  'Newmarket-on-Fergus': 'Clare',
  'Ennis': 'Clare',
  'Shannon': 'Clare',
  'Kilrush': 'Clare',
  'Kilkee': 'Clare',
  'Lahinch': 'Clare',
  'Miltown Malbay': 'Clare',
  'Quilty': 'Clare',
  'Doonbeg': 'Clare',
  'Kilbaha': 'Clare',
  'Carrigaholt': 'Clare',
  'Kilkee': 'Clare',
  'Liscannor': 'Clare',
  'Doolin': 'Clare',
  'Ballyvaughan': 'Clare',
  'Fanore': 'Clare',
  'Lisdoonvarna': 'Clare',
  'Ballyvaughan': 'Clare',
  'Corofin': 'Clare',
  'Ennistymon': 'Clare',
  'Kilfenora': 'Clare',
  'Inagh': 'Clare',
  'Ennistymon': 'Clare',
  'Killaloe': 'Clare',
  'Scariff': 'Clare',
  'Mountshannon': 'Clare',
  'Whitegate': 'Clare',
  'Feakle': 'Clare',
  'Tulla': 'Clare',
  'Bodyke': 'Clare',
  'Broadford': 'Clare',
  'Sixmilebridge': 'Clare',
  'Newmarket-on-Fergus': 'Clare',
  'Quin': 'Clare',
  'Tulla': 'Clare',
  
  // Mayo
  'Castlebar': 'Mayo',
  'Ballina': 'Mayo',
  'Westport': 'Mayo',
  'Claremorris': 'Mayo',
  'Ballinrobe': 'Mayo',
  'Swinford': 'Mayo',
  'Kiltimagh': 'Mayo',
  'Castlebar': 'Mayo',
  'Ballina': 'Mayo',
  'Westport': 'Mayo',
  'Claremorris': 'Mayo',
  'Ballinrobe': 'Mayo',
  'Swinford': 'Mayo',
  'Kiltimagh': 'Mayo',
  'Ballyhaunis': 'Mayo',
  'Charlestown': 'Mayo',
  'Foxford': 'Mayo',
  'Newport': 'Mayo',
  'Mulranny': 'Mayo',
  'Achill Sound': 'Mayo',
  'Keel': 'Mayo',
  'Dooagh': 'Mayo',
  'Dooega': 'Mayo',
  'Dugort': 'Mayo',
  'Ballycroy': 'Mayo',
  'Belmullet': 'Mayo',
  'Bangor Erris': 'Mayo',
  'Crossmolina': 'Mayo',
  'Ballina': 'Mayo',
  'Killala': 'Mayo',
  'Ballycastle': 'Mayo',
  'Lahardane': 'Mayo',
  'Addergoole': 'Mayo',
  'Knock': 'Mayo',
  'Ballyhaunis': 'Mayo',
  'Claremorris': 'Mayo',
  'Balla': 'Mayo',
  'Manulla': 'Mayo',
  'Turlough': 'Mayo',
  'Ballinrobe': 'Mayo',
  'Cong': 'Mayo',
  'Headford': 'Galway', // Close to Mayo border
  
  // Sligo
  'Sligo': 'Sligo',
  'Ballymote': 'Sligo',
  'Tubbercurry': 'Sligo',
  'Collooney': 'Sligo',
  'Sligo': 'Sligo',
  'Ballymote': 'Sligo',
  'Tubbercurry': 'Sligo',
  'Collooney': 'Sligo',
  'Ballysadare': 'Sligo',
  'Strandhill': 'Sligo',
  'Rosses Point': 'Sligo',
  'Drumcliff': 'Sligo',
  'Grange': 'Sligo',
  'Cliffoney': 'Sligo',
  'Mullaghmore': 'Sligo',
  'Gurteen': 'Sligo',
  'Bunninadden': 'Sligo',
  'Coolaney': 'Sligo',
  'Dromore West': 'Sligo',
  'Easkey': 'Sligo',
  'Enniscrone': 'Sligo',
  'Ballisodare': 'Sligo',
  
  // Donegal
  'Letterkenny': 'Donegal',
  'Ballybofey': 'Donegal',
  'Buncrana': 'Donegal',
  'Bundoran': 'Donegal',
  'Donegal': 'Donegal',
  'Dungloe': 'Donegal',
  'Moville': 'Donegal',
  'Letterkenny': 'Donegal',
  'Ballybofey': 'Donegal',
  'Stranorlar': 'Donegal',
  'Buncrana': 'Donegal',
  'Bundoran': 'Donegal',
  'Donegal': 'Donegal',
  'Dungloe': 'Donegal',
  'Moville': 'Donegal',
  'Carndonagh': 'Donegal',
  'Ballyliffin': 'Donegal',
  'Clonmany': 'Donegal',
  'Muff': 'Donegal',
  'Quigley\'s Point': 'Donegal',
  'Redcastle': 'Donegal',
  'Fahan': 'Donegal',
  'Burnfoot': 'Donegal',
  'Bridgend': 'Donegal',
  'Newtowncunningham': 'Donegal',
  'Raphoe': 'Donegal',
  'Lifford': 'Donegal',
  'St Johnston': 'Donegal',
  'Carrigans': 'Donegal',
  'Killea': 'Donegal',
  'Newtowncunningham': 'Donegal',
  'Manorhamilton': 'Leitrim', // Close to Donegal border
  'Milford': 'Donegal',
  'Ramelton': 'Donegal',
  'Rathmullan': 'Donegal',
  'Downings': 'Donegal',
  'Carrigart': 'Donegal',
  'Dunfanaghy': 'Donegal',
  'Falcarragh': 'Donegal',
  'Gortahork': 'Donegal',
  'Dunlewey': 'Donegal',
  'Crolly': 'Donegal',
  'Dungloe': 'Donegal',
  'Glenties': 'Donegal',
  'Ardara': 'Donegal',
  'Killybegs': 'Donegal',
  'Mountcharles': 'Donegal',
  'Donegal': 'Donegal',
  'Laghy': 'Donegal',
  'Ballyshannon': 'Donegal',
  'Bundoran': 'Donegal',
  'Rossnowlagh': 'Donegal',
  'Ballyshannon': 'Donegal',
  
  // Leitrim
  'Carrick-on-Shannon': 'Leitrim',
  'Manorhamilton': 'Leitrim',
  'Ballinamore': 'Leitrim',
  'Carrick-on-Shannon': 'Leitrim',
  'Manorhamilton': 'Leitrim',
  'Ballinamore': 'Leitrim',
  'Drumshanbo': 'Leitrim',
  'Dromahair': 'Leitrim',
  'Kinlough': 'Leitrim',
  'Tullaghan': 'Leitrim',
  'Rossinver': 'Leitrim',
  'Glenfarne': 'Leitrim',
  'Kiltyclogher': 'Leitrim',
  'Dowra': 'Leitrim',
  'Blacklion': 'Cavan', // Close to Leitrim border
  'Swanlinbar': 'Cavan', // Close to Leitrim border
  'Mohill': 'Leitrim',
  'Carrigallen': 'Leitrim',
  'Aughavas': 'Leitrim',
  'Cloone': 'Leitrim',
  'Gortletteragh': 'Leitrim',
  'Fenagh': 'Leitrim',
  'Aughrim': 'Leitrim',
  'Keshcarrigan': 'Leitrim',
  
  // Roscommon
  'Roscommon': 'Roscommon',
  'Boyle': 'Roscommon',
  'Castlerea': 'Roscommon',
  'Strokestown': 'Roscommon',
  'Roscommon': 'Roscommon',
  'Boyle': 'Roscommon',
  'Castlerea': 'Roscommon',
  'Strokestown': 'Roscommon',
  'Elphin': 'Roscommon',
  'Tulsk': 'Roscommon',
  'Ballaghaderreen': 'Roscommon',
  'Frenchpark': 'Roscommon',
  'Boyle': 'Roscommon',
  'Carrick-on-Shannon': 'Leitrim', // Close to Roscommon border
  'Athleague': 'Roscommon',
  'Monksland': 'Roscommon',
  'Lanesborough': 'Longford', // Close to Roscommon border
  'Ballyleague': 'Roscommon',
  'Lecarrow': 'Roscommon',
  'Knockcroghery': 'Roscommon',
  'Rahara': 'Roscommon',
  'Ballyforan': 'Roscommon',
  'Ballinasloe': 'Galway', // Close to Roscommon border
  'Creggs': 'Galway', // Close to Roscommon border
  
  // Longford
  'Longford': 'Longford',
  'Ballymahon': 'Longford',
  'Edgeworthstown': 'Longford',
  'Longford': 'Longford',
  'Ballymahon': 'Longford',
  'Edgeworthstown': 'Longford',
  'Granard': 'Longford',
  'Newtownforbes': 'Longford',
  'Drumlish': 'Longford',
  'Ballinalee': 'Longford',
  'Clondra': 'Longford',
  'Legan': 'Longford',
  'Abbeyshrule': 'Longford',
  'Ballymahon': 'Longford',
  'Moydow': 'Longford',
  'Killashee': 'Longford',
  'Ardagh': 'Longford',
  'Carrickboy': 'Longford',
  
  // Westmeath
  'Athlone': 'Westmeath',
  'Mullingar': 'Westmeath',
  'Moate': 'Westmeath',
  'Kilbeggan': 'Westmeath',
  'Athlone': 'Westmeath',
  'Mullingar': 'Westmeath',
  'Moate': 'Westmeath',
  'Kilbeggan': 'Westmeath',
  'Rochfortbridge': 'Westmeath',
  'Castlepollard': 'Westmeath',
  'Collinstown': 'Westmeath',
  'Coole': 'Westmeath',
  'Ballinahown': 'Westmeath',
  'Ballymore': 'Westmeath',
  'Ballynacargy': 'Westmeath',
  'Delvin': 'Westmeath',
  'Fore': 'Westmeath',
  'Killucan': 'Westmeath',
  'Rathwire': 'Westmeath',
  'Tyrellspass': 'Westmeath',
  'Mullingar': 'Westmeath',
  'Ballinea': 'Westmeath',
  'Lough Owel': 'Westmeath',
  'Lough Ennell': 'Westmeath',
  
  // Offaly
  'Tullamore': 'Offaly',
  'Birr': 'Offaly',
  'Edenderry': 'Offaly',
  'Banagher': 'Offaly',
  'Tullamore': 'Offaly',
  'Birr': 'Offaly',
  'Edenderry': 'Offaly',
  'Banagher': 'Offaly',
  'Clara': 'Offaly',
  'Kilcormac': 'Offaly',
  'Kinnitty': 'Offaly',
  'Shinrone': 'Offaly',
  'Roscrea': 'Tipperary', // Close to Offaly border
  'Moneygall': 'Tipperary', // Close to Offaly border
  'Portarlington': 'Laois', // Close to Offaly border
  'Daingean': 'Offaly',
  'Ballycumber': 'Offaly',
  'Ferbane': 'Offaly',
  'Shannonbridge': 'Offaly',
  'Cloghan': 'Offaly',
  'Banagher': 'Offaly',
  'Lusmagh': 'Offaly',
  'Shannon Harbour': 'Offaly',
  'Ballinamore': 'Offaly',
  'Geashill': 'Offaly',
  'Killeigh': 'Offaly',
  'Rahan': 'Offaly',
  'Mucklagh': 'Offaly',
  'Ballyboy': 'Offaly',
  'Kilclonfert': 'Offaly',
  'Clonbullogue': 'Offaly',
  'Edenderry': 'Offaly',
  'Clonmore': 'Offaly',
  'Cadamstown': 'Offaly',
  'Kinnitty': 'Offaly',
  'Ballybritt': 'Offaly',
  
  // Laois
  'Portlaoise': 'Laois',
  'Mountmellick': 'Laois',
  'Portarlington': 'Laois',
  'Abbeyleix': 'Laois',
  'Portlaoise': 'Laois',
  'Mountmellick': 'Laois',
  'Portarlington': 'Laois',
  'Abbeyleix': 'Laois',
  'Stradbally': 'Laois',
  'Ballylinan': 'Laois',
  'Barrowhouse': 'Laois',
  'Ballyroan': 'Laois',
  'Ballinakill': 'Laois',
  'Durrow': 'Laois',
  'Cullahill': 'Laois',
  'Castletown': 'Laois',
  'Mountrath': 'Laois',
  'Ballyfin': 'Laois',
  'Rosenallis': 'Laois',
  'Clonaslee': 'Laois',
  'Mountmellick': 'Laois',
  'Portlaoise': 'Laois',
  'Portarlington': 'Laois',
  'Emo': 'Laois',
  'Monasterevin': 'Kildare', // Close to Laois border
  'Athy': 'Kildare', // Close to Laois border
  
  // Carlow
  'Carlow': 'Carlow',
  'Tullow': 'Carlow',
  'Muine Bheag': 'Carlow',
  'Carlow': 'Carlow',
  'Tullow': 'Carlow',
  'Muine Bheag': 'Carlow',
  'Bagenalstown': 'Carlow',
  'Leighlinbridge': 'Carlow',
  'Borris': 'Carlow',
  'Hacketstown': 'Carlow',
  'Tullow': 'Carlow',
  'Rathvilly': 'Carlow',
  'Ballon': 'Carlow',
  'Clonegal': 'Carlow',
  'Kildavin': 'Carlow',
  'Fenagh': 'Carlow',
  'Myshall': 'Carlow',
  'Ballinkillen': 'Carlow',
  'Killeshin': 'Laois', // Close to Carlow border
  
  // Cavan
  'Cavan': 'Cavan',
  'Belturbet': 'Cavan',
  'Cootehill': 'Cavan',
  'Ballyjamesduff': 'Cavan',
  'Cavan': 'Cavan',
  'Belturbet': 'Cavan',
  'Cootehill': 'Cavan',
  'Ballyjamesduff': 'Cavan',
  'Virginia': 'Cavan',
  'Bailieborough': 'Cavan',
  'Kingscourt': 'Cavan',
  'Shercock': 'Cavan',
  'Carrickmacross': 'Monaghan', // Close to Cavan border
  'Ballybay': 'Monaghan', // Close to Cavan border
  'Mullagh': 'Cavan',
  'Killeshandra': 'Cavan',
  'Arvagh': 'Cavan',
  'Dowra': 'Leitrim', // Close to Cavan border
  'Blacklion': 'Cavan',
  'Swanlinbar': 'Cavan',
  'Ballyconnell': 'Cavan',
  'Bawnboy': 'Cavan',
  'Templeport': 'Cavan',
  'Crossdoney': 'Cavan',
  'Butlersbridge': 'Cavan',
  'Killashandra': 'Cavan',
  'Lough Gowna': 'Cavan',
  'Mountnugent': 'Cavan',
  'Oldcastle': 'Meath', // Close to Cavan border
  
  // Monaghan
  'Monaghan': 'Monaghan',
  'Carrickmacross': 'Monaghan',
  'Castleblayney': 'Monaghan',
  'Clones': 'Monaghan',
  'Monaghan': 'Monaghan',
  'Carrickmacross': 'Monaghan',
  'Castleblayney': 'Monaghan',
  'Clones': 'Monaghan',
  'Ballybay': 'Monaghan',
  'Emyvale': 'Monaghan',
  'Scotshouse': 'Monaghan',
  'Newbliss': 'Monaghan',
  'Smithborough': 'Monaghan',
  'Rockcorry': 'Monaghan',
  'Inniskeen': 'Monaghan',
  'Drum': 'Monaghan',
  'Emyvale': 'Monaghan',
  'Aughnamullen': 'Monaghan',
  'Donagh': 'Monaghan',
  'Tydavnet': 'Monaghan',
  'Corcaghan': 'Monaghan',
  'Ballybay': 'Monaghan',
  'Carrickmacross': 'Monaghan',
  'Castleblayney': 'Monaghan',
  'Clones': 'Monaghan',
  
  // Northern Ireland counties (included for completeness)
  'Belfast': 'Antrim',
  'Lisburn': 'Antrim',
  'Carrickfergus': 'Antrim',
  'Larne': 'Antrim',
  'Ballymena': 'Antrim',
  'Coleraine': 'Derry',
  'Derry': 'Derry',
  'Londonderry': 'Derry',
  'Newry': 'Down',
  'Downpatrick': 'Down',
  'Banbridge': 'Down',
  'Armagh': 'Armagh',
  'Portadown': 'Armagh',
  'Lurgan': 'Armagh',
  'Enniskillen': 'Fermanagh',
  'Omagh': 'Tyrone',
  'Strabane': 'Tyrone',
  'Dungannon': 'Tyrone',
}

// Get all town names as an array (sorted)
export const TOWN_NAMES = Object.keys(IRISH_TOWNS).sort()

// Get county for a town
export function getCountyForTown(town: string): string | null {
  return IRISH_TOWNS[town] || null
}

// Search towns by query (case-insensitive)
export function searchTowns(query: string): string[] {
  if (!query.trim()) return []
  const lowerQuery = query.toLowerCase()
  return TOWN_NAMES.filter(town => 
    town.toLowerCase().includes(lowerQuery)
  ).slice(0, 10) // Limit to 10 results
}

